// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_doublet_chunk_cpp
List fast_doublet_chunk_cpp(NumericMatrix beads, NumericVector nUMI, NumericMatrix ref_profiles, NumericMatrix all_weights, LogicalVector conv_all, IntegerVector class_ids, NumericMatrix Q_mat, NumericMatrix SQ_mat, NumericVector X_vals, int K_val, bool constrain, double min_change, double confidence_threshold, double doublet_threshold, bool return_diagnostics, int max_cores);
RcppExport SEXP _spacexrfast_fast_doublet_chunk_cpp(SEXP beadsSEXP, SEXP nUMISEXP, SEXP ref_profilesSEXP, SEXP all_weightsSEXP, SEXP conv_allSEXP, SEXP class_idsSEXP, SEXP Q_matSEXP, SEXP SQ_matSEXP, SEXP X_valsSEXP, SEXP K_valSEXP, SEXP constrainSEXP, SEXP min_changeSEXP, SEXP confidence_thresholdSEXP, SEXP doublet_thresholdSEXP, SEXP return_diagnosticsSEXP, SEXP max_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type beads(beadsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nUMI(nUMISEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ref_profiles(ref_profilesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type all_weights(all_weightsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type conv_all(conv_allSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type class_ids(class_idsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Q_mat(Q_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type SQ_mat(SQ_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X_vals(X_valsSEXP);
    Rcpp::traits::input_parameter< int >::type K_val(K_valSEXP);
    Rcpp::traits::input_parameter< bool >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< double >::type min_change(min_changeSEXP);
    Rcpp::traits::input_parameter< double >::type confidence_threshold(confidence_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type doublet_threshold(doublet_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type return_diagnostics(return_diagnosticsSEXP);
    Rcpp::traits::input_parameter< int >::type max_cores(max_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_doublet_chunk_cpp(beads, nUMI, ref_profiles, all_weights, conv_all, class_ids, Q_mat, SQ_mat, X_vals, K_val, constrain, min_change, confidence_threshold, doublet_threshold, return_diagnostics, max_cores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spacexrfast_fast_doublet_chunk_cpp", (DL_FUNC) &_spacexrfast_fast_doublet_chunk_cpp, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_spacexrfast(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
