# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_doublet_chunk_cpp <- function(beads, nUMI, ref_profiles, all_weights, conv_all, class_ids, Q_mat, SQ_mat, X_vals, K_val, constrain, min_change, confidence_threshold, doublet_threshold, return_diagnostics, max_cores) {
    .Call(`_spacexrfast_fast_doublet_chunk_cpp`, beads, nUMI, ref_profiles, all_weights, conv_all, class_ids, Q_mat, SQ_mat, X_vals, K_val, constrain, min_change, confidence_threshold, doublet_threshold, return_diagnostics, max_cores)
}

